services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1GB
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  postgres:
      image: postgres
      container_name: postgres
      ports:
        - "15432:5432"
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: P@ssw0rd